// Auto-generated by LibreLane
module mac_engine_2(
`ifdef USE_POWER_PINS
  inout vccd1,
  inout vssd1,
`endif
  input clk,
  input rst_n,
  input s_axis_tvalid,
  output s_axis_tready,
  input[31:0] s_axis_tdata,
  input s_axis_tuser,
  output m_axis_tvalid,
  input m_axis_tready,
  output[39:0] m_axis_tdata
);
endmodule
