###############################################################################
# Created by write_sdc
###############################################################################
current_design mac_engine_2
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 10.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tready}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rst_n}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[0]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[10]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[11]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[12]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[13]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[14]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[15]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[16]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[17]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[18]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[19]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[1]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[20]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[21]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[22]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[23]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[24]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[25]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[26]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[27]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[28]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[29]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[2]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[30]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[31]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[3]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[4]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[5]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[6]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[7]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[8]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tdata[9]}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tuser}]
set_input_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tvalid}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[0]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[10]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[11]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[12]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[13]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[14]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[15]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[16]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[17]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[18]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[19]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[1]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[20]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[21]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[22]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[23]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[24]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[25]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[26]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[27]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[28]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[29]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[2]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[30]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[31]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[32]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[33]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[34]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[35]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[36]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[37]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[38]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[39]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[3]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[4]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[5]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[6]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[7]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[8]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tdata[9]}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {m_axis_tvalid}]
set_output_delay 2.0000 -clock [get_clocks {clk}] -add_delay [get_ports {s_axis_tready}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {m_axis_tvalid}]
set_load -pin_load 0.0334 [get_ports {s_axis_tready}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[39]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[38]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[37]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[36]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[35]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[34]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[33]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[32]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[31]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[30]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[29]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[28]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[27]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[26]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[25]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[24]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[23]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[22]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[21]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[20]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[19]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[18]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[17]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[16]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[15]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[14]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[13]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[12]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[11]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[10]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[9]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[8]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[7]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[6]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[5]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[4]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[3]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[2]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[1]}]
set_load -pin_load 0.0334 [get_ports {m_axis_tdata[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {m_axis_tready}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst_n}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tuser}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tvalid}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {s_axis_tdata[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 1.5000 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 9.0000 [current_design]
